//go:build windows

package dwrite

type FactoryType uint32

const (
	DWRITE_FACTORY_TYPE_SHARED   FactoryType = 0
	DWRITE_FACTORY_TYPE_ISOLATED FactoryType = 1
)

type FontWeight uint32

const (
	DWRITE_FONT_WEIGHT_THIN        FontWeight = 100
	DWRITE_FONT_WEIGHT_EXTRA_LIGHT FontWeight = 200
	DWRITE_FONT_WEIGHT_ULTRA_LIGHT FontWeight = 200
	DWRITE_FONT_WEIGHT_LIGHT       FontWeight = 300
	DWRITE_FONT_WEIGHT_SEMI_LIGHT  FontWeight = 350
	DWRITE_FONT_WEIGHT_NORMAL      FontWeight = 400
	DWRITE_FONT_WEIGHT_REGULAR     FontWeight = 400
	DWRITE_FONT_WEIGHT_MEDIUM      FontWeight = 500
	DWRITE_FONT_WEIGHT_DEMI_BOLD   FontWeight = 600
	DWRITE_FONT_WEIGHT_SEMI_BOLD   FontWeight = 600
	DWRITE_FONT_WEIGHT_BOLD        FontWeight = 700
	DWRITE_FONT_WEIGHT_EXTRA_BOLD  FontWeight = 800
	DWRITE_FONT_WEIGHT_ULTRA_BOLD  FontWeight = 800
	DWRITE_FONT_WEIGHT_BLACK       FontWeight = 900
	DWRITE_FONT_WEIGHT_HEAVY       FontWeight = 900
	DWRITE_FONT_WEIGHT_EXTRA_BLACK FontWeight = 950
	DWRITE_FONT_WEIGHT_ULTRA_BLACK FontWeight = 950
)

type FontStyle uint32

const (
	DWRITE_FONT_STYLE_NORMAL  FontStyle = 0
	DWRITE_FONT_STYLE_OBLIQUE FontStyle = 1
	DWRITE_FONT_STYLE_ITALIC  FontStyle = 2
)

type FontStretch uint32

const (
	DWRITE_FONT_STRETCH_UNDEFINED       FontStretch = 0
	DWRITE_FONT_STRETCH_ULTRA_CONDENSED FontStretch = 1
	DWRITE_FONT_STRETCH_EXTRA_CONDENSED FontStretch = 2
	DWRITE_FONT_STRETCH_CONDENSED       FontStretch = 3
	DWRITE_FONT_STRETCH_SEMI_CONDENSED  FontStretch = 4
	DWRITE_FONT_STRETCH_NORMAL          FontStretch = 5
	DWRITE_FONT_STRETCH_MEDIUM          FontStretch = 5
	DWRITE_FONT_STRETCH_SEMI_EXPANDED   FontStretch = 6
	DWRITE_FONT_STRETCH_EXPANDED        FontStretch = 7
	DWRITE_FONT_STRETCH_EXTRA_EXPANDED  FontStretch = 8
	DWRITE_FONT_STRETCH_ULTRA_EXPANDED  FontStretch = 9
)

type TextAlignment uint32

const (
	DWRITE_TEXT_ALIGNMENT_LEADING   TextAlignment = 0
	DWRITE_TEXT_ALIGNMENT_TRAILING  TextAlignment = 1
	DWRITE_TEXT_ALIGNMENT_CENTER    TextAlignment = 2
	DWRITE_TEXT_ALIGNMENT_JUSTIFIED TextAlignment = 3
)

type ParagraphAlignment uint32

const (
	DWRITE_PARAGRAPH_ALIGNMENT_NEAR   ParagraphAlignment = 0
	DWRITE_PARAGRAPH_ALIGNMENT_FAR    ParagraphAlignment = 1
	DWRITE_PARAGRAPH_ALIGNMENT_CENTER ParagraphAlignment = 2
)
